//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocietyProfiler.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SocietyProfiler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shawn
        ///Sean
        ///Shaun
        ///Paul
        ///Kale
        ///Eric
        ///Erik
        ///Dan
        ///Daniel
        ///Cam
        ///Jimmy
        ///James
        ///Thomas
        ///John
        ///Jon.
        /// </summary>
        internal static string names_boys {
            get {
                return ResourceManager.GetString("names_boys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annika
        ///Rachel
        ///Lilly
        ///Sara
        ///Sarah
        ///Caroline
        ///Michelle
        ///Jeannine
        ///Jeanne
        ///Janice
        ///Janet
        ///Christine
        ///Nora.
        /// </summary>
        internal static string names_girls {
            get {
                return ResourceManager.GetString("names_girls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matthews
        ///Pietsch
        ///Stephens
        ///Stevens
        ///Owens
        ///Bussandwich
        ///Sistermans
        ///Lafleur
        ///Amyotte
        ///Flaxon Jackson Waxon.
        /// </summary>
        internal static string names_last {
            get {
                return ResourceManager.GetString("names_last", resourceCulture);
            }
        }
    }
}
